### ISSUE TITLE
Date selectors seem to have no effect

### ISSUE THREAD

**Issue by mjray** [cyclestreets/streetfocus#2]
I've tried just putting the year (which seems to be what the html source implies), I've tried using 2022-01-01 format and 01/01/2022 format (which seems to be what the PlanIt API docs imply) and I've tried leaving one field blank. The map stays the same and I struggle to see the live trees for the old dead wood (to twist a metaphor) and there are some live applications shown, so it seems like the data is being updated. What am I doing wrong? Is there a bug in the code or just the missing documentation?

I'm looking at the area around King's Lynn, in case that matters.

**Comment by mvl22** [comment]
This got fixed; the UI had got out of sync with the API spec. There's also a slider now.

Thanks for reporting this.
